package by.epamtc.shamuradova.ishop.controller.command;

public enum ParameterNameCommand {
	SAVE_NEW_SHOPPER, 
	WELCOME_USER, 
	SIGN_IN, 
	SET_LOCALE, 
	REGISTRATION_PAGE, 
	GET_SHOPPER_PAGE, 
	GET_ERROR_PAGE,
	GET_ADMIN_PAGE,
	GET_MAIN_ALL_MODELS_PAGE,
	LOAD_MORE_MODELS,
	MODELS_BY_CATEGORY,
	ENTER_PAGE,
	MODEL_PAGE_MODAL,
	ADD_TO_CARD
	
	

}
