package by.epamtc.shamuradova.ishop.controller.command;

public enum ParameterNameCommand {
	SAVE_NEW_SHOPPER, 
	WELCOME_USER, 
	SIGN_IN, 
	SET_LOCALE, 
	REGISTRATION_PAGE, 
	GET_SHOPPER_PAGE, 
	GET_ERROR_PAGE,
	GET_ADMIN_PAGE,
	GET_MAIN_ALL_MODELS_PAGE,
	LOAD_MORE_MODELS,
	MODELS_BY_CATEGORY,
	ENTER_PAGE,
	MODEL_PAGE_MODAL,
	ADD_TO_CART,
	CART_PAGE,
	SIGN_OUT,
	REDUCE_COUNT_OF_GOODS_PER_UNIT,
	INCREASE_COUNT_OF_GOODS_PER_UNIT,
	FORM_ORDER,
	CREATE_ORDER,
	MY_ORDERS, //ожет переименовать на all
	LOAD_MORE_ORDERS,
	ORDER_DETAILES
	

}
